Repository localhelp/findlocal.help, pull requests merged in 2020-04, with the labels that each got.

#12 created basic structure Index.html.erb, _banner _card _search-form
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_search_form.scss
  app/views/application/index.html.erb
  app/views/shared/_banner.html.erb
  app/views/shared/_card.html.erb
  app/views/shared/_search_form.html.erb
Labels: to merge! 🚀

#13 Cloudinary
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_fonts.scss
  app/models/task.rb
  app/models/user.rb
  config/environments/development.rb
  config/environments/production.rb
  config/storage.yml
  db/migrate/20200410161014_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: to merge 🚀

#11 Added controllers and routes
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/task_applications_controller.rb
  app/controllers/task_tags_controller.rb
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/user.rb
  app/views/pages/index.html.erb
  app/views/task/index.html.erb
  config/routes.rb
  test/controllers/pages_controller_test.rb
  test/controllers/tags_controller_test.rb
  test/controllers/task_applications_controller_test.rb
  test/controllers/task_tags_controller_test.rb
  test/controllers/tasks_controller_test.rb
Labels: to review

#18 Dashboard
  app/assets/stylesheets/pages/_home.scss
  app/controllers/helps_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/tasks_controller.rb
  app/views/pages/dashboard.html.erb
  app/views/shared/_creator_task_modal.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: to merge 🚀
